<?php

class PermissionsTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('permissions')->truncate();
        
		\DB::table('permissions')->insert(array (
			0 => 
			array (
				'id' => '10',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'TemplateController@anyIndex',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			1 => 
			array (
				'id' => '11',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'TemplateController@anyTree',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			2 => 
			array (
				'id' => '12',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ContentsController@anyIndex',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			3 => 
			array (
				'id' => '13',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ContentsController@anyTree',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			4 => 
			array (
				'id' => '14',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ContentsController@anyEdit',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			5 => 
			array (
				'id' => '15',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'TemplateController@anyEdit',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			6 => 
			array (
				'id' => '16',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'UsersController@anyDashboard',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			7 => 
			array (
				'id' => '17',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'UsersController@anyIndex',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			8 => 
			array (
				'id' => '18',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'UsersController@anyLogout',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			9 => 
			array (
				'id' => '19',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'UsersController@anySettings',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			10 => 
			array (
				'id' => '21',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'UsersController@anyCreate',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			11 => 
			array (
				'id' => '23',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'UsersController@anyStore',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			12 => 
			array (
				'id' => '25',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'UsersController@anyUpdate',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			13 => 
			array (
				'id' => '27',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'TemplateController@anyCreate',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			14 => 
			array (
				'id' => '28',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ContentsController@anyStore',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			15 => 
			array (
				'id' => '29',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ContentsController@anyCreate',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			16 => 
			array (
				'id' => '30',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'TemplateController@anyStore',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			17 => 
			array (
				'id' => '31',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'TemplateController@anyUpdate',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			18 => 
			array (
				'id' => '32',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ContentsController@anyUpdate',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			19 => 
			array (
				'id' => '33',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ContentsController@anyDestroy',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			20 => 
			array (
				'id' => '34',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'TemplateController@anyDestroy',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			21 => 
			array (
				'id' => '35',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'TemplateController@deleteUpload',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			22 => 
			array (
				'id' => '36',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ContentsController@deleteUpload',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			23 => 
			array (
				'id' => '37',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ContentsController@postUpload',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			24 => 
			array (
				'id' => '38',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'TemplateController@postUpload',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			25 => 
			array (
				'id' => '39',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ApplicationController@anyCreate',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			26 => 
			array (
				'id' => '40',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ApplicationController@postStore',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			27 => 
			array (
				'id' => '41',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ApplicationController@anySettings',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			28 => 
			array (
				'id' => '42',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ApplicationController@anyUpdate',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			29 => 
			array (
				'id' => '43',
				'requestor_id' => '*',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'RemindersController@getRemind',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			30 => 
			array (
				'id' => '44',
				'requestor_id' => '*',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'RemindersController@postRemind',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			31 => 
			array (
				'id' => '45',
				'requestor_id' => '*',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'RemindersController@getReset',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			32 => 
			array (
				'id' => '46',
				'requestor_id' => '*',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'RemindersController@postReset',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			33 => 
			array (
				'id' => '48',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ContentsController@anyFixtree',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			34 => 
			array (
				'id' => '49',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ReportsController@anyIndex',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			35 => 
			array (
				'id' => '50',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ReportsController@anyRun',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			36 => 
			array (
				'id' => '51',
				'requestor_id' => '2',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ReportsController@anyEdit',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
			37 => 
			array (
				'id' => '52',
				'requestor_id' => '*',
				'application_id' => '',
				'requestor_type' => 'role',
				'controller_id' => '*',
				'controller_type' => 'ReportsController@anyQueryOptions',
				'x' => '1',
				'comment' => '',
				'created_at' => date("Y-m-d H:i:s"),
				'updated_at' => date("Y-m-d H:i:s"),
			),
		));
	}

}
